// flow-typed signature: bcf9d11470b48f5f6cb8236433479164
// flow-typed version: <<STUB>>/babel-upgrade_v^0.0.23/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-upgrade'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-upgrade' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-upgrade/lib/bin' {
  declare module.exports: any;
}

declare module 'babel-upgrade/lib/index' {
  declare module.exports: any;
}

declare module 'babel-upgrade/lib/packageData' {
  declare module.exports: any;
}

declare module 'babel-upgrade/lib/upgradeConfig' {
  declare module.exports: any;
}

declare module 'babel-upgrade/lib/upgradeDeps' {
  declare module.exports: any;
}

declare module 'babel-upgrade/lib/upgradeOptions' {
  declare module.exports: any;
}

declare module 'babel-upgrade/src/bin' {
  declare module.exports: any;
}

declare module 'babel-upgrade/src/index' {
  declare module.exports: any;
}

declare module 'babel-upgrade/src/packageData' {
  declare module.exports: any;
}

declare module 'babel-upgrade/src/upgradeConfig' {
  declare module.exports: any;
}

declare module 'babel-upgrade/src/upgradeDeps' {
  declare module.exports: any;
}

declare module 'babel-upgrade/src/upgradeOptions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-upgrade/lib/bin.js' {
  declare module.exports: $Exports<'babel-upgrade/lib/bin'>;
}
declare module 'babel-upgrade/lib/index.js' {
  declare module.exports: $Exports<'babel-upgrade/lib/index'>;
}
declare module 'babel-upgrade/lib/packageData.js' {
  declare module.exports: $Exports<'babel-upgrade/lib/packageData'>;
}
declare module 'babel-upgrade/lib/upgradeConfig.js' {
  declare module.exports: $Exports<'babel-upgrade/lib/upgradeConfig'>;
}
declare module 'babel-upgrade/lib/upgradeDeps.js' {
  declare module.exports: $Exports<'babel-upgrade/lib/upgradeDeps'>;
}
declare module 'babel-upgrade/lib/upgradeOptions.js' {
  declare module.exports: $Exports<'babel-upgrade/lib/upgradeOptions'>;
}
declare module 'babel-upgrade/src/bin.js' {
  declare module.exports: $Exports<'babel-upgrade/src/bin'>;
}
declare module 'babel-upgrade/src/index.js' {
  declare module.exports: $Exports<'babel-upgrade/src/index'>;
}
declare module 'babel-upgrade/src/packageData.js' {
  declare module.exports: $Exports<'babel-upgrade/src/packageData'>;
}
declare module 'babel-upgrade/src/upgradeConfig.js' {
  declare module.exports: $Exports<'babel-upgrade/src/upgradeConfig'>;
}
declare module 'babel-upgrade/src/upgradeDeps.js' {
  declare module.exports: $Exports<'babel-upgrade/src/upgradeDeps'>;
}
declare module 'babel-upgrade/src/upgradeOptions.js' {
  declare module.exports: $Exports<'babel-upgrade/src/upgradeOptions'>;
}
