// flow-typed signature: b99b42557a4b449035bde1f6ff02ba4b
// flow-typed version: <<STUB>>/flexible-pwa-webpack-plugin_v^0.0.10/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flexible-pwa-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flexible-pwa-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flexible-pwa-webpack-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'flexible-pwa-webpack-plugin/dist/lib/helpers' {
  declare module.exports: any;
}

declare module 'flexible-pwa-webpack-plugin/dist/lib/icons' {
  declare module.exports: any;
}

declare module 'flexible-pwa-webpack-plugin/dist/lib/manifest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flexible-pwa-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'flexible-pwa-webpack-plugin/dist/index'>;
}
declare module 'flexible-pwa-webpack-plugin/dist/lib/helpers.js' {
  declare module.exports: $Exports<'flexible-pwa-webpack-plugin/dist/lib/helpers'>;
}
declare module 'flexible-pwa-webpack-plugin/dist/lib/icons.js' {
  declare module.exports: $Exports<'flexible-pwa-webpack-plugin/dist/lib/icons'>;
}
declare module 'flexible-pwa-webpack-plugin/dist/lib/manifest.js' {
  declare module.exports: $Exports<'flexible-pwa-webpack-plugin/dist/lib/manifest'>;
}
declare module 'flexible-pwa-webpack-plugin/index' {
  declare module.exports: $Exports<'flexible-pwa-webpack-plugin'>;
}
declare module 'flexible-pwa-webpack-plugin/index.js' {
  declare module.exports: $Exports<'flexible-pwa-webpack-plugin'>;
}
