// flow-typed signature: e57f397a7edd19171f8e3e67d6dce766
// flow-typed version: <<STUB>>/webpack-polyfill-injector_v^2.0.2/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-polyfill-injector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-polyfill-injector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-polyfill-injector/src/helpers' {
  declare module.exports: any;
}

declare module 'webpack-polyfill-injector/src/injector-multi' {
  declare module.exports: any;
}

declare module 'webpack-polyfill-injector/src/injector-single' {
  declare module.exports: any;
}

declare module 'webpack-polyfill-injector/src/loader' {
  declare module.exports: any;
}

declare module 'webpack-polyfill-injector/src/plugin' {
  declare module.exports: any;
}

declare module 'webpack-polyfill-injector/src/PluginState' {
  declare module.exports: any;
}

declare module 'webpack-polyfill-injector/test/fixtures/entry' {
  declare module.exports: any;
}

declare module 'webpack-polyfill-injector/test/fixtures/entry2' {
  declare module.exports: any;
}

declare module 'webpack-polyfill-injector/test/fixtures/entry3' {
  declare module.exports: any;
}

declare module 'webpack-polyfill-injector/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-polyfill-injector/src/helpers.js' {
  declare module.exports: $Exports<'webpack-polyfill-injector/src/helpers'>;
}
declare module 'webpack-polyfill-injector/src/injector-multi.js' {
  declare module.exports: $Exports<'webpack-polyfill-injector/src/injector-multi'>;
}
declare module 'webpack-polyfill-injector/src/injector-single.js' {
  declare module.exports: $Exports<'webpack-polyfill-injector/src/injector-single'>;
}
declare module 'webpack-polyfill-injector/src/loader.js' {
  declare module.exports: $Exports<'webpack-polyfill-injector/src/loader'>;
}
declare module 'webpack-polyfill-injector/src/plugin.js' {
  declare module.exports: $Exports<'webpack-polyfill-injector/src/plugin'>;
}
declare module 'webpack-polyfill-injector/src/PluginState.js' {
  declare module.exports: $Exports<'webpack-polyfill-injector/src/PluginState'>;
}
declare module 'webpack-polyfill-injector/test/fixtures/entry.js' {
  declare module.exports: $Exports<'webpack-polyfill-injector/test/fixtures/entry'>;
}
declare module 'webpack-polyfill-injector/test/fixtures/entry2.js' {
  declare module.exports: $Exports<'webpack-polyfill-injector/test/fixtures/entry2'>;
}
declare module 'webpack-polyfill-injector/test/fixtures/entry3.js' {
  declare module.exports: $Exports<'webpack-polyfill-injector/test/fixtures/entry3'>;
}
declare module 'webpack-polyfill-injector/test/test.js' {
  declare module.exports: $Exports<'webpack-polyfill-injector/test/test'>;
}
